### ISSUE TITLE
Why you don't use modelviewset or generics for API?

### ISSUE THREAD

**Issue by aliesm-com** [amirhamiri/wall#1]
Hi Amir, How's Everything?

I just watched your project and see you are using APIView Instead of ModelViewSet for Listview CreateView and Detail View.

Do you have any reason to use these? you can do all of them with generics too but you create all of them from start.

If It's Okay I wanna to update your code to one the choices - ModelViewSet or Generics.

**Comment by amirhamiri** [comment]
Hey dear Ali,
Just for code integrity. Using APIView makes it easier to understand everything that happens inside the codes. In real projects, you usually need to customize generic views, so it's better to start simple and customized from the beginning.
If a person has a little familiarity with Django, he can easily recognize at a glance what's happening in your project, while when using generic views, he's forced to study their mechanism.
And of course it's very important that your codes are written according to a specific structure and using different classes in different views is not very interesting.
thank you.

**Comment by aliesm-com** [comment]
Hello again,
I said you can also use generics.
You can use ModelViewSet and actions for these kind of work you just said.

By the way, thank you for responding. ✌️
